"""AIGC 检测：离线启发式检测引擎 + 报告导出。"""

from paper_agent.services.aigc.analyzer import (  # noqa: F401
    DEFAULT_SENSITIVITY,
    DOCUMENT_FILTER,
    ENGINE_NAME,
    KIND_BODY,
    KIND_HEADING,
    KIND_REFERENCE,
    LEVEL_AI,
    LEVEL_COLORS,
    LEVEL_HUMAN,
    LEVEL_LABELS,
    LEVEL_ORDER,
    LEVEL_SUSPECT,
    SENSITIVITY_PRESETS,
    SUPPORTED_SUFFIXES,
    AigcReport,
    LayoutParagraph,
    SentenceVerdict,
    analyze_file,
    analyze_text,
    risk_of,
)
from paper_agent.services.aigc.report import export_report_pdf  # noqa: F401
from paper_agent.services.aigc.records import (  # noqa: F401
    AigcRecord,
    AigcRecordStore,
    record_from_dict,
    report_from_dict,
    report_to_dict,
)

__all__ = [
    "AigcRecord",
    "AigcRecordStore",
    "AigcReport",
    "DEFAULT_SENSITIVITY",
    "DOCUMENT_FILTER",
    "ENGINE_NAME",
    "KIND_BODY",
    "KIND_HEADING",
    "KIND_REFERENCE",
    "LEVEL_AI",
    "LEVEL_COLORS",
    "LEVEL_HUMAN",
    "LEVEL_LABELS",
    "LEVEL_ORDER",
    "LEVEL_SUSPECT",
    "LayoutParagraph",
    "SENSITIVITY_PRESETS",
    "SUPPORTED_SUFFIXES",
    "SentenceVerdict",
    "analyze_file",
    "analyze_text",
    "export_report_pdf",
    "record_from_dict",
    "report_from_dict",
    "report_to_dict",
    "risk_of",
]
